apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-shop
  template:
    metadata:
      labels:
        app: e-shop
    spec:
      containers:
      - name: e-shop
        image: techmafia/e-shop:latest  # Updated image name
        ports:
        - containerPort: 3000
